import Head from "next/head";
import Navbar from "../components/navbar-dl";
import Landinghero from "../components/hero/landing";
import CategoryCard from "../components/categoryCard";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Tinsel | Heritage Teas</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Landinghero />
      <Navbar/>
      <div className="text-center mt-10 mb-4 text-3xl font-serif font-semibold text-slate-800">Discover our Teas</div>
      <CategoryCard />
      <div className="h-screen"></div>
    </div>
  );
}
