import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/Navbar/index"

export default function Home() {
  return (
    <div className="m-12">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex justify-center">
        <h1 className="font-serif font-semibold text-4xl text-slate-800">
          Welcome to Tinsel!
        </h1>
      </div>

      <Navbar/>
    </div>
  );
}
